An exception occured in <%= PP.pp(@processor, '') -%>!

<%= "#{@message}\n\n" if @message -%>
<%= @error.class.name -%>: <%= @error.message %>

<%= @error.backtrace.join("\n\t") %>
